"""Added column for upvote count

Revision ID: 11a571934c82
Revises: a23fbce0dfd5
Create Date: 2026-01-29 18:38:36.627259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a571934c82'
down_revision: Union[str, Sequence[str], None] = 'a23fbce0dfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('upvote_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'upvote_count')
    # ### end Alembic commands ###
