"""added firstname and lastname to user model

Revision ID: 680dc40a5465
Revises: b995f172bd53
Create Date: 2026-01-20 04:46:06.756357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "680dc40a5465"
down_revision: Union[str, Sequence[str], None] = "b995f172bd53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("firstName", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("lastName", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "lastName")
    op.drop_column("users", "firstName")
    # ### end Alembic commands ###
