"""Changed 'report_status' column to 'verificiation_status' and 'image_url' to 'media_url' 

Revision ID: d0a9d020d0c2
Revises: 1ffdf63bbc66
Create Date: 2026-01-24 18:24:50.453593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0a9d020d0c2"
down_revision: Union[str, Sequence[str], None] = "1ffdf63bbc66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories",
        "name",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.add_column("reports", sa.Column("media_url", sa.String(), nullable=True))
    op.add_column(
        "reports", sa.Column("verification_status", sa.String(), nullable=False)
    )
    op.drop_column("reports", "report_status")
    op.drop_column("reports", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reports",
        sa.Column("report_status", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("reports", "verification_status")
    op.drop_column("reports", "media_url")
    op.alter_column(
        "categories",
        "name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
