"""Added 'severity' column to report table 

Revision ID: e1d527c081ec
Revises: d0a9d020d0c2
Create Date: 2026-01-24 18:52:16.579752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1d527c081ec"
down_revision: Union[str, Sequence[str], None] = "d0a9d020d0c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("severity", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "severity")
    # ### end Alembic commands ###
